[package]
name = "adventOfCode2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "util/utils" }
pprof = { version = "0.4", features = ["flamegraph"] }